---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: conjur
spec:
  provider:
    conjur:
      # Service URL
      url: https://conjur.pocpuppy.nl
      # [OPTIONAL] base64 encoded string of certificate
      # caBundle: OPTIONALxFIELDxxxBase64xCertxString==
      auth:
        jwt:
          # conjur account
          account: admin
          # The authn-jwt service ID
          serviceID: Conjur_TeamA_OpenShift
          # Service account to retrieve JWT token for
          serviceAccountRef:
            name: jwt-eso-service-account-conjur-team-a
            # [OPTIONAL] audiences to include in JWT token
            audiences:
              - https://conjur.pocpuppy.nl
