---
name: CI/CD Pipeline
on:
  push:

jobs:
  conjur-who-ami:
    runs-on: proxnuccis19
    steps:
      - name: Import Secrets using CyberArk Conjur Secret Fetcher Action  # yamllint disable-line rule:line-length
        uses: cyberark/conjur-action@v2.0.5
        with:
          url: ${{ vars.CONJUR_URL_INTERNAL }}
          account: ${{ vars.CONJUR_ACCOUNT }}
          host_id: ${{ vars.CONJUR_HOST_USERNAME }}
          api_key: ${{ secrets.CONJUR_HOST_API_KEY }}
          secrets: ${{ vars.CONJUR_USERNAME_PATH }}|conjur_username;${{ vars.CONJUR_PASSWORD_PATH }}|conjur_password  # yamllint disable-line rule:line-length
          certificate: ${{ vars.CONJUR_CERT }}

      - name: Check out code from GitHub
        uses: actions/checkout@v3

      - name: Trigger Conjur Policy load - init
        run: |
          mv lib/conjur-cli-go_8.0.19_linux_amd64 conjur
          chmod +x conjur
          ./conjur --version
          echo "yes" | ./conjur init -u ${{ vars.CONJUR_URL_INTERNAL }} -a ${{ vars.CONJUR_ACCOUNT }} --force --self-signed
          ./conjur login -i $CONJUR_USERNAME -p $CONJUR_PASSWORD
          ./conjur whoami
