---
name: CI/CD Pipeline
on:
  push:

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    name: Echo Test
    steps:
      - name: Check branch name
        run: |
          echo "Test"

      - name: Check branch name
        run: |
          curl https://conjur.pocpuppy.nl
